version: '3.8'

services:
  redis:
    image: redis:7
    container_name: peerquest-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  backend:
    build:
      context: ./PeerQuestBackEnd
    container_name: peerquest-backend
    volumes:
      - ./PeerQuestBackEnd:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    env_file:
      - ./PeerQuestBackEnd/.env
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings

  frontend:
    build:
      context: ./PeerQuestFrontEnd
    container_name: peerquest-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./PeerQuestFrontEnd/.env.local
    environment:
      - NODE_ENV=development
    volumes:
      - ./PeerQuestFrontEnd:/app
      - /app/node_modules

  mysql:
    image: mysql:8
    container_name: peerquest-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: peerquestdb
      MYSQL_USER: peerquestuser
      MYSQL_PASSWORD: peerquestpass
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
