
services:
  backend:
    build:
      context: ./PeerQuestBackEnd
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=peerquest
      - MYSQL_USER=root
      - MYSQL_PASSWORD=yourpassword
      - REDIS_URL=redis://default:yourredispassword@redis:6379
    depends_on:
      - mysql
      - redis

  frontend:
    build:
      context: ./PeerQuestFrontEnd
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pq@2025deployET
      MYSQL_DATABASE: peerquest
    ports:
      - "3306:3306"

  redis:
    image: redis:7
    restart: always
    ports:
      - "6379:6379"
