services:
  - type: web
    name: peerquest-frontend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: true
    buildFilter:
      paths:
        - PeerQuestFrontEnd/**
    repo: https://github.com/EmTech-PeerQuest/PeerQuestWebsite.git
    branch: main
    rootDir: PeerQuestFrontEnd
    autoDeploy: true

  - type: web
    name: peerquest-backend
    env: python
    plan: starter
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: daphne -b 0.0.0.0 -p 8000 core.asgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: PYTHONUNBUFFERED
        value: 1
      - key: PYTHONDONTWRITEBYTECODE
        value: 1
      - key: DB_NAME
        value: railway
      - key: DB_USER
        value: root
      - key: DB_PASSWORD
        value: eDSQimrlTQUYHUfLAUafONopsFQCwxem
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: REDIS_URL
        value: redis://default:your_redis_password@peerquest-redis.internal:6379
    buildFilter:
      paths:
        - PeerQuestBackEnd/**
    repo: https://github.com/EmTech-PeerQuest/PeerQuestWebsite.git
    branch: main
    rootDir: PeerQuestBackEnd
    autoDeploy: true

  - type: redis
    name: peerquest-redis
    plan: starter
    ipAllowList:
      - source: 0.0.0.0/0
        description: allow all internal services
