# Generated by Django 5.2.3 on 2025-06-30 07:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0016_quest_quests_ques_assigne_557d69_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, help_text='Application message')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Application status', max_length=15)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Application submission time')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Application review time', null=True)),
                ('applicant', models.ForeignKey(help_text='Quest applicant', on_delete=django.db.models.deletion.CASCADE, related_name='quest_applications', to=settings.AUTH_USER_MODEL)),
                ('quest', models.ForeignKey(help_text='Applied quest', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='quests.quest')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Reviewer (quest creator)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
                'indexes': [models.Index(fields=['quest', 'status'], name='application_quest_i_169413_idx'), models.Index(fields=['applicant', 'status'], name='application_applica_b6966f_idx'), models.Index(fields=['applied_at'], name='application_applied_06e426_idx')],
                'unique_together': {('quest', 'applicant')},
            },
        ),
    ]
