# Generated by Django 5.2.4 on 2025-07-09 18:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('kicked', 'Kicked')], default='pending', help_text='Application status', max_length=15)),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Application submission time')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Application review time', null=True)),
                ('applicant', models.ForeignKey(help_text='Quest applicant', on_delete=django.db.models.deletion.CASCADE, related_name='quest_applications', to=settings.AUTH_USER_MODEL)),
                ('quest', models.ForeignKey(help_text='Applied quest', on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='quests.quest')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Reviewer (quest creator)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(help_text='Sequential attempt number for this user/quest combination')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this attempt was made')),
                ('applicant', models.ForeignKey(help_text='User making the application attempt', on_delete=django.db.models.deletion.CASCADE, related_name='application_attempts', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(help_text='The application record this attempt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='applications.application')),
                ('quest', models.ForeignKey(help_text='Quest being applied to', on_delete=django.db.models.deletion.CASCADE, related_name='application_attempts', to='quests.quest')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['quest', 'status'], name='application_quest_i_169413_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applicant', 'status'], name='application_applica_b6966f_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['applied_at'], name='application_applied_06e426_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['quest', 'applicant'], name='application_quest_i_de9482_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationattempt',
            index=models.Index(fields=['quest', 'applicant'], name='application_quest_i_1ec8b3_idx'),
        ),
        migrations.AddIndex(
            model_name='applicationattempt',
            index=models.Index(fields=['applicant', 'timestamp'], name='application_applica_943478_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='applicationattempt',
            unique_together={('quest', 'applicant', 'attempt_number')},
        ),
    ]
