# Generated by Django 5.2.3 on 2025-07-01 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_remove_message_field'),
        ('quests', '0021_make_application_message_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['quest', 'applicant'], name='application_quest_i_de9482_idx'),
        ),
    ]
