# Generated by Django 5.2.3 on 2025-07-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_remove_unique_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('kicked', 'Kicked')], default='pending', help_text='Application status', max_length=15),
        ),
    ]
