# Generated by Django 5.2.3 on 2025-07-07 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_status'),
        ('quests', '0031_questsubmissionattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_number', models.PositiveIntegerField(help_text='Sequential attempt number for this user/quest combination')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When this attempt was made')),
                ('applicant', models.ForeignKey(help_text='User making the application attempt', on_delete=django.db.models.deletion.CASCADE, related_name='application_attempts', to=settings.AUTH_USER_MODEL)),
                ('application', models.ForeignKey(help_text='The application record this attempt belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='applications.application')),
                ('quest', models.ForeignKey(help_text='Quest being applied to', on_delete=django.db.models.deletion.CASCADE, related_name='application_attempts', to='quests.quest')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['quest', 'applicant'], name='application_quest_i_1ec8b3_idx'), models.Index(fields=['applicant', 'timestamp'], name='application_applica_943478_idx')],
                'unique_together': {('quest', 'applicant', 'attempt_number')},
            },
        ),
    ]
