# Generated by Django 5.2.3 on 2025-07-11 16:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_url', models.URLField(blank=True, max_length=255)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], default='common', max_length=10)),
                ('points_value', models.IntegerField(default=0)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rarity', 'name'],
            },
        ),
        migrations.AddField(
            model_name='userachievement',
            name='awarded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='users.achievement'),
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement_name',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='achievement_type',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='description',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='icon_url',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='points_value',
        ),
        migrations.RemoveField(
            model_name='userachievement',
            name='rarity',
        ),
    ]
