# Generated by Django 5.2.3 on 2025-07-05 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthday_user_display_name_user_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
