# Generated by Django 5.2.3 on 2025-07-12 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_achievement_userachievement_awarded_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='experience_points',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gold_balance',
        ),
    ]
