# Generated by Django 5.2.3 on 2025-07-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='backup_codes_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='spending_limits',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(blank=True, default='email', max_length=20),
        ),
    ]
