# Generated by Django 5.2.3 on 2025-07-13 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_create_guild_report'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuildReportNew',
        ),
    ]
