# Generated by Django 5.2.3 on 2025-06-24 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('oauth2_provider', '0012_add_token_checksum'),
        ('social_django', '0016_alter_usersocialauth_extra_data'),
        ('users', '0004_user_userachievement_userskill_delete_newuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='NewUser',
        ),
    ]
