# Generated by Django 5.2.3 on 2025-07-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_goldtransaction_xptransaction'),
        ('users', '0005_auto_20250713_1217'),
    ]

    operations = [
    ]
