# Generated by Django 5.2.3 on 2025-07-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20250713_1642'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='guildreport',
            table=None,
        ),
    ]
