# Generated by Django 5.2.3 on 2025-07-07 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_banappeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banappeal',
            name='file',
        ),
        migrations.CreateModel(
            name='BanAppealFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='ban_appeals/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.banappeal')),
            ],
        ),
    ]
