# Generated by Django 5.2.3 on 2025-07-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_redundant_gold_balance'),
        ('users', '0010_skill_alter_userskill_options_user_role_and_more'),
    ]

    operations = [
    ]
