# Generated by Django 5.2.3 on 2025-07-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_merge_20250707_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gold_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
