# Generated by Django 5.2.3 on 2025-07-07 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_actionlog'),
        ('users', '0011_remove_banappeal_file_banappealfile'),
    ]

    operations = [
    ]
