# Generated by Django 5.2.3 on 2025-07-08 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_merge_20250707_1756'),
        ('users', '0012_user_gold_balance'),
    ]

    operations = [
    ]
