# Generated by Django 5.2.3 on 2025-06-27 02:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='guild_avatars/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='guild_banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True, help_text='Whether the guild is publicly visible')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_guilds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GuildMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('owner', 'Owner')], default='member', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('can_post_quests', models.BooleanField(default=False, help_text='Can create quests on behalf of the guild')),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guilds.guild')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='guild',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='guilds', through='guilds.GuildMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='guildmembership',
            index=models.Index(fields=['guild', 'role'], name='guilds_guil_guild_i_f8efe6_idx'),
        ),
        migrations.AddIndex(
            model_name='guildmembership',
            index=models.Index(fields=['user', 'role'], name='guilds_guil_user_id_10471b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guildmembership',
            unique_together={('guild', 'user')},
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(fields=['name'], name='guilds_guil_name_722234_idx'),
        ),
        migrations.AddIndex(
            model_name='guild',
            index=models.Index(fields=['is_active', 'is_public'], name='guilds_guil_is_acti_a6b6c2_idx'),
        ),
    ]
