# Generated by Django 5.2.3 on 2025-07-09 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('guilds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_guilds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guildjoinrequest',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='guilds.guild'),
        ),
        migrations.AddField(
            model_name='guildjoinrequest',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guildjoinrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_join_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guildmembership',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guildmembership',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='guilds.guild'),
        ),
        migrations.AddField(
            model_name='guildmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guild_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guildsociallink',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='guilds.guild'),
        ),
        migrations.AddField(
            model_name='guildtag',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='guilds.guild'),
        ),
        migrations.AlterUniqueTogether(
            name='guildjoinrequest',
            unique_together={('guild', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='guildmembership',
            unique_together={('guild', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='guildsociallink',
            unique_together={('guild', 'platform_name')},
        ),
        migrations.AlterUniqueTogether(
            name='guildtag',
            unique_together={('guild', 'tag')},
        ),
    ]
