# Generated by Django 5.2.3 on 2025-06-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
        ('quests', '0011_remove_quest_post_as_remove_quest_posted_by_guild_and_more'),
    ]

    operations = [
        # No-op migration - guild models were already removed
    ]
