# Generated by Django 5.2.4 on 2025-07-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='emblem',
            field=models.ImageField(blank=True, null=True, upload_to='guild_emblems/'),
        ),
        migrations.AddField(
            model_name='guild',
            name='join_requirements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='guild',
            name='permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='guild',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='guild',
            name='social_links',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='guild',
            name='specialization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='guild',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='guild',
            name='visibility',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='guild',
            name='welcome_message',
            field=models.TextField(blank=True),
        ),
    ]
