# Generated by Django 5.2.3 on 2025-06-27 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_remove_guildmembership_guild_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guildmembership',
            name='guild',
        ),
        migrations.AlterUniqueTogether(
            name='guildmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='guildmembership',
            name='user',
        ),
        migrations.DeleteModel(
            name='Guild',
        ),
        migrations.DeleteModel(
            name='GuildMembership',
        ),
    ]
