# Generated by Django 5.2.3 on 2025-07-05 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_remove_guildmembership_guild_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='guild',
            name='guilds_guil_name_722234_idx',
        ),
        migrations.RemoveIndex(
            model_name='guild',
            name='guilds_guil_is_acti_a6b6c2_idx',
        ),
        migrations.RemoveIndex(
            model_name='guildmembership',
            name='guilds_guil_guild_i_f8efe6_idx',
        ),
        migrations.RemoveIndex(
            model_name='guildmembership',
            name='guilds_guil_user_id_10471b_idx',
        ),
    ]
