# Generated by Django 5.2.3 on 2025-07-12 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0003_guildreport'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GuildReport',
        ),
    ]
