# Generated by Django 5.2.3 on 2025-07-13 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guilds', '0002_guild_members_guildchatmessage'),
        ('guilds', '0004_delete_guildreport'),
    ]

    operations = [
    ]
