# Generated by Django 5.2.4 on 2025-07-09 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference', models.CharField(max_length=50, unique=True)),
                ('package_amount', models.IntegerField()),
                ('package_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_image', models.ImageField(upload_to='payment_receipts/')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='queued', max_length=20)),
                ('batch_id', models.CharField(blank=True, max_length=50, null=True)),
                ('scheduled_batch', models.CharField(blank=True, choices=[('morning', 'Morning Batch'), ('afternoon', 'Afternoon Batch'), ('evening', 'Evening Batch'), ('late_night', 'Late Night Batch')], max_length=20, null=True)),
                ('next_processing_time', models.DateTimeField(blank=True, null=True)),
                ('verification_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Proof',
                'verbose_name_plural': 'Payment Proofs',
                'ordering': ['-created_at'],
            },
        ),
    ]
