# Generated by Django 5.2.3 on 2025-07-06 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Verification'), ('queued', 'Queued for Batch Processing'), ('processing', 'Being Processed'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
