# Generated by Django 5.2.3 on 2025-07-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gold_amount', models.IntegerField()),
                ('price_php', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonus_gold', models.IntegerField(default=0)),
                ('bonus_description', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Gold Package',
                'verbose_name_plural': 'Gold Packages',
                'ordering': ['price_php'],
            },
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='bonus',
            field=models.CharField(blank=True, help_text='Bonus description (for record keeping)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='package_amount',
            field=models.IntegerField(help_text='Gold coins from package (for record keeping)'),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='package_price',
            field=models.DecimalField(decimal_places=2, help_text='Price paid in PHP (for record keeping)', max_digits=10),
        ),
        migrations.AddField(
            model_name='paymentproof',
            name='gold_package',
            field=models.ForeignKey(blank=True, help_text='Selected gold package with fixed pricing', null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.goldpackage'),
        ),
    ]
