# Generated by Django 5.2.3 on 2025-07-06 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_paymentproof_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='scheduled_batch',
            field=models.CharField(blank=True, choices=[('morning', 'Morning Batch'), ('afternoon', 'Afternoon Batch'), ('evening', 'Evening Batch'), ('late_night', 'Late Night Batch')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='paymentproof',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
