# Generated by Django 5.2.3 on 2025-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_goldpackage_alter_paymentproof_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='gold_awarded',
            field=models.BooleanField(default=False, help_text='Has gold been awarded for this payment?'),
        ),
    ]
