# Generated by Django 5.2.3 on 2025-07-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_paymentproof_scheduled_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('queued', 'Queued'), ('processing', 'Processing'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
