# Generated by Django 5.2.3 on 2025-07-12 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentproof_gold_awarded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentproof',
            name='gold_awarded',
        ),
    ]
