# Generated by Django 5.2.3 on 2025-07-06 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_completed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentproof',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='queued', max_length=20),
        ),
    ]
