# Generated by Django 5.2.3 on 2025-07-12 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0006_questcompletionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestGoldReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Reserved gold amount', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_reservation', to='quests.quest')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(help_text='Primary key, auto-increment', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('PURCHASE', 'Purchase'), ('REWARD', 'Reward'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('CASHOUT', 'Cashout'), ('QUEST_REWARD', 'Quest Reward')], default='PURCHASE', help_text='Transaction type', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('commission_fee', models.DecimalField(decimal_places=2, default=0, help_text='Commission fee amount (if applicable)', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='Transaction description', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Transaction time')),
                ('quest', models.ForeignKey(blank=True, help_text='Related quest (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='quests.quest')),
                ('user', models.ForeignKey(help_text='Transaction user', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_gold', models.DecimalField(decimal_places=2, help_text='Amount of gold to cash out', max_digits=10)),
                ('amount_php', models.DecimalField(decimal_places=2, help_text='Equivalent amount in PHP (calculated at time of request)', max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=0.07, help_text='Exchange rate used (gold to PHP)', max_digits=6)),
                ('method', models.CharField(choices=[('GCASH', 'GCash'), ('PAYMAYA', 'PayMaya'), ('BANK', 'Bank Transfer')], help_text='Cashout method', max_length=20)),
                ('payment_details', models.TextField(blank=True, help_text='Payment details (account number, etc.)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Cashout status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes or rejection reason', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Request creation time')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Time when request was processed', null=True)),
                ('user', models.ForeignKey(help_text='User requesting cashout', on_delete=django.db.models.deletion.CASCADE, related_name='cashout_requests', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(blank=True, help_text='Associated transaction record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashout_request', to='transactions.transaction')),
            ],
            options={
                'verbose_name': 'Cashout Request',
                'verbose_name_plural': 'Cashout Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current gold balance', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
