# Generated by Django 5.2.3 on 2025-07-05 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0023_alter_quest_difficulty_alter_quest_xp_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(help_text='Primary key, auto-increment', primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('QUEST_REWARD', 'Quest Reward'), ('QUEST_BONUS', 'Quest Bonus'), ('PURCHASE', 'Purchase'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('GIFT', 'Gift'), ('OTHER', 'Other')], default='OTHER', help_text='Transaction type', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=10)),
                ('description', models.CharField(blank=True, help_text='Transaction description', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Transaction time')),
                ('quest', models.ForeignKey(blank=True, help_text='Related quest (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='quests.quest')),
                ('user', models.ForeignKey(help_text='Transaction user', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gold_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Current gold balance', max_digits=12)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
                ('user', models.OneToOneField(help_text='User', on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
