# Generated by Django 5.2.3 on 2025-07-05 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0023_alter_quest_difficulty_alter_quest_xp_reward'),
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestGoldReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Reserved gold amount', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gold_reservation', to='quests.quest')),
            ],
        ),
    ]
