# Generated by Django 5.2.3 on 2025-07-11 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashoutMethodConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('GCASH', 'GCash'), ('PAYMAYA', 'PayMaya'), ('BANK', 'Bank Transfer')], help_text='Cashout method identifier', max_length=20, unique=True)),
                ('display_name', models.CharField(help_text='Display name for the method', max_length=100)),
                ('description', models.CharField(help_text='Brief description of the method', max_length=255)),
                ('processing_time', models.CharField(help_text='Expected processing time (e.g., "24-48 hours")', max_length=100)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=5000.0, help_text='Minimum cashout amount in gold', max_digits=10)),
                ('maximum_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum cashout amount in gold (null = no limit)', max_digits=10, null=True)),
                ('fee_percentage', models.DecimalField(decimal_places=4, default=0.0, help_text='Fee percentage (0.0000 = free)', max_digits=5)),
                ('fee_fixed', models.DecimalField(decimal_places=2, default=0.0, help_text='Fixed fee amount in PHP', max_digits=10)),
                ('requires_verification', models.BooleanField(default=False, help_text='Whether this method requires identity verification')),
                ('verification_threshold', models.DecimalField(blank=True, decimal_places=2, help_text='PHP amount threshold that triggers verification requirement', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this method is currently available')),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular method (for UI highlighting)')),
                ('icon_name', models.CharField(blank=True, help_text='Icon identifier for frontend (e.g., "smartphone", "credit-card", "building")', max_length=50, null=True)),
                ('instructions', models.TextField(blank=True, help_text='Special instructions or notes for this method', null=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cashout Method Configuration',
                'verbose_name_plural': 'Cashout Method Configurations',
                'ordering': ['sort_order', 'method'],
            },
        ),
        migrations.AddField(
            model_name='cashoutrequest',
            name='method_config',
            field=models.ForeignKey(blank=True, help_text='Reference to method configuration at time of request', null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.cashoutmethodconfig'),
        ),
    ]
