# Generated by Django 5.2.3 on 2025-07-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_questgoldreservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('QUEST_REWARD', 'Quest Reward'), ('PURCHASE', 'Purchase'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('GIFT', 'Gift'), ('OTHER', 'Other')], default='OTHER', help_text='Transaction type', max_length=20),
        ),
    ]
