# Generated by Django 5.2.3 on 2025-07-05 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('QUEST_REWARD', 'Quest Reward'), ('QUEST_CREATION', 'Quest Creation'), ('QUEST_REFUND', 'Quest Refund'), ('PURCHASE', 'Purchase'), ('ADMIN_ADJUSTMENT', 'Admin Adjustment'), ('GIFT', 'Gift'), ('OTHER', 'Other')], default='OTHER', help_text='Transaction type', max_length=20),
        ),
    ]
