# Generated by Django 5.2.3 on 2025-07-12 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentproof_gold_awarded'),
        ('transactions', '0003_alter_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_proof',
            field=models.OneToOneField(blank=True, help_text='Related payment proof for purchase (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction', to='payments.paymentproof'),
        ),
    ]
