# Generated by Django 5.2.3 on 2025-07-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('REWARD', 'Reward'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund')], default='PURCHASE', help_text='Transaction type', max_length=20),
        ),
    ]
