# Generated by Django 5.2.3 on 2025-07-07 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_transaction_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('REWARD', 'Reward'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('CASHOUT', 'Cashout')], default='PURCHASE', help_text='Transaction type', max_length=20),
        ),
        migrations.CreateModel(
            name='CashoutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_gold', models.DecimalField(decimal_places=2, help_text='Amount of gold to cash out', max_digits=10)),
                ('amount_php', models.DecimalField(decimal_places=2, help_text='Equivalent amount in PHP (calculated at time of request)', max_digits=10)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=0.07, help_text='Exchange rate used (gold to PHP)', max_digits=6)),
                ('method', models.CharField(choices=[('GCASH', 'GCash'), ('PAYMAYA', 'PayMaya'), ('BANK', 'Bank Transfer')], help_text='Cashout method', max_length=20)),
                ('payment_details', models.TextField(blank=True, help_text='Payment details (account number, etc.)', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', help_text='Cashout status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Admin notes or rejection reason', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Request creation time')),
                ('processed_at', models.DateTimeField(blank=True, help_text='Time when request was processed', null=True)),
                ('transaction', models.OneToOneField(blank=True, help_text='Associated transaction record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashout_request', to='transactions.transaction')),
                ('user', models.ForeignKey(help_text='User requesting cashout', on_delete=django.db.models.deletion.CASCADE, related_name='cashout_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cashout Request',
                'verbose_name_plural': 'Cashout Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
