# Generated by Django 5.2.3 on 2025-07-07 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_transaction_type_cashoutrequest'),
    ]

    operations = [
    ]
