# Generated by Django 5.2.3 on 2025-07-07 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_increase_gold_balance_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbalance',
            name='gold_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Current gold balance', max_digits=12),
        ),
    ]
