# Generated by Django 5.2.3 on 2025-07-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_revert_gold_balance_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='base_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Base amount before commission (if applicable)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='commission_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Commission fee amount (if applicable)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('REWARD', 'Reward'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('CASHOUT', 'Cashout'), ('COMMISSION', 'Commission Fee')], default='PURCHASE', help_text='Transaction type', max_length=20),
        ),
    ]
