# Generated by Django 5.2.3 on 2025-07-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_add_commission_tracking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='base_amount',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('PURCHASE', 'Purchase'), ('REWARD', 'Reward'), ('TRANSFER', 'Transfer'), ('REFUND', 'Refund'), ('CASHOUT', 'Cashout')], default='PURCHASE', help_text='Transaction type', max_length=20),
        ),
    ]
