# Generated by Django 5.2.3 on 2025-06-26 11:27

from django.db import migrations


def add_quest_categories(apps, schema_editor):
    """Add initial quest categories"""
    QuestCategory = apps.get_model('quests', 'QuestCategory')
    
    categories = [
        {
            'name': 'Design',
            'description': 'Visual design, UX/UI, graphic design, and creative projects'
        },
        {
            'name': 'Development',
            'description': 'Programming, software development, web development, and technical projects'
        },
        {
            'name': 'Writing',
            'description': 'Content creation, copywriting, documentation, and written communication'
        },
        {
            'name': 'Music',
            'description': 'Music composition, audio production, sound design, and musical projects'
        },
        {
            'name': 'Art',
            'description': 'Traditional and digital art, illustration, photography, and artistic endeavors'
        },
        {
            'name': 'Marketing',
            'description': 'Digital marketing, social media, SEO, advertising, and promotional activities'
        },
        {
            'name': 'Research',
            'description': 'Data analysis, market research, academic research, and investigative projects'
        }
    ]
    
    for category_data in categories:
        QuestCategory.objects.get_or_create(
            name=category_data['name'],
            defaults={'description': category_data['description']}
        )


def remove_quest_categories(apps, schema_editor):
    """Remove the quest categories (reverse operation)"""
    QuestCategory = apps.get_model('quests', 'QuestCategory')
    category_names = ['Design', 'Development', 'Writing', 'Music', 'Art', 'Marketing', 'Research']
    
    QuestCategory.objects.filter(name__in=category_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_quest_categories, remove_quest_categories),
    ]
