# Generated by Django 5.2.4 on 2025-07-09 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User currently assigned to this quest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quest',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_quests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quest',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='quests.questcategory'),
        ),
        migrations.AddField(
            model_name='questparticipant',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quests.quest'),
        ),
        migrations.AddField(
            model_name='questparticipant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_participations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quest',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participating_quests', through='quests.QuestParticipant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questsubmission',
            name='quest_participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='quests.questparticipant'),
        ),
        migrations.AddField(
            model_name='questsubmission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questsubmissionattempt',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_attempts', to='quests.questparticipant'),
        ),
        migrations.AddField(
            model_name='questsubmissionattempt',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_attempts', to='quests.quest'),
        ),
        migrations.AddField(
            model_name='questsubmissionattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='questparticipant',
            index=models.Index(fields=['quest', 'status'], name='quests_ques_quest_i_cda784_idx'),
        ),
        migrations.AddIndex(
            model_name='questparticipant',
            index=models.Index(fields=['user', 'status'], name='quests_ques_user_id_c2f5b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questparticipant',
            unique_together={('quest', 'user')},
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['status', 'difficulty'], name='quests_ques_status_1610b2_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['creator', 'status'], name='quests_ques_creator_c79dec_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['assigned_to', 'status'], name='quests_ques_assigne_557d69_idx'),
        ),
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['created_at'], name='quests_ques_created_57a5fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='questsubmissionattempt',
            unique_together={('participant', 'quest', 'user', 'timestamp')},
        ),
    ]
