# Generated by Django 5.2.3 on 2025-06-26 11:29

from django.db import migrations


def remove_backend_category(apps, schema_editor):
    """Remove the Backend category and update any quests that reference it"""
    QuestCategory = apps.get_model('quests', 'QuestCategory')
    Quest = apps.get_model('quests', 'Quest')
    
    # Get the Backend category
    try:
        backend_category = QuestCategory.objects.get(name='Backend')
        
        # Get a replacement category (Design as it's the first in our list)
        replacement_category = QuestCategory.objects.get(name='Design')
        
        # Update any quests that use the Backend category to use Design instead
        Quest.objects.filter(category=backend_category).update(category=replacement_category)
        
        # Delete the Backend category
        backend_category.delete()
        
    except QuestCategory.DoesNotExist:
        # Backend category doesn't exist, nothing to do
        pass


def restore_backend_category(apps, schema_editor):
    """Restore the Backend category (reverse operation)"""
    QuestCategory = apps.get_model('quests', 'QuestCategory')
    
    # Recreate the Backend category
    QuestCategory.objects.get_or_create(
        name='Backend',
        defaults={'description': 'Backend development and server-side programming'}
    )


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_add_quest_categories'),
    ]

    operations = [
        migrations.RunPython(remove_backend_category, restore_backend_category),
    ]
