# Generated by Django 5.2.3 on 2025-06-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0003_remove_backend_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
    ]
