# Generated by Django 5.2.3 on 2025-06-26 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_alter_quest_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='priority',
        ),
    ]
