# Generated by Django 5.2.3 on 2025-07-11 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0004_add_default_quest_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='gold_reward',
            field=models.PositiveIntegerField(default=0, help_text='Gold coins awarded upon completion', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
