# Generated by Django 5.2.3 on 2025-06-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_remove_priority_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='xp_reward',
            field=models.PositiveIntegerField(choices=[(50, '50 XP'), (75, '75 XP'), (150, '150 XP')], default=50, help_text='XP points awarded upon completion'),
        ),
    ]
