# Generated by Django 5.2.3 on 2025-07-12 10:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0005_alter_quest_gold_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestCompletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp_earned', models.PositiveIntegerField()),
                ('gold_earned', models.PositiveIntegerField()),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('adventurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_completions', to=settings.AUTH_USER_MODEL)),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to='quests.quest')),
            ],
            options={
                'ordering': ['-completed_at'],
                'unique_together': {('quest', 'adventurer')},
            },
        ),
    ]
