# Generated by Django 5.2.3 on 2025-06-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0007_alter_quest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='quest',
            name='due_date',
            field=models.DateField(blank=True, help_text='Deadline date for quest completion', null=True),
        ),
    ]
