# Generated by Django 5.2.3 on 2025-06-26 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0008_remove_quest_start_date_alter_quest_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='gold_reward',
            field=models.PositiveIntegerField(default=0, help_text='Gold coins awarded upon completion (0-999)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)]),
        ),
    ]
