# Generated by Django 5.2.3 on 2025-06-27 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0009_quest_gold_reward'),
    ]

    operations = [
        # No-op migration - guild fields were removed in 0011
    ]
