# Generated by Django 5.2.3 on 2025-06-27 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0010_quest_post_as_quest_posted_by_guild'),
    ]

    operations = [
        # No-op migration - fields were already removed/never added
    ]
