# Generated by Django 5.2.3 on 2025-06-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0011_remove_quest_post_as_remove_quest_posted_by_guild_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='short_description',
        ),
    ]
