# Generated by Django 5.2.3 on 2025-06-27 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0012_remove_quest_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='quests.questcategory'),
        ),
    ]
