# Generated by Django 5.2.3 on 2025-06-28 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0013_alter_quest_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='estimated_time',
        ),
    ]
