# Generated by Django 5.2.3 on 2025-06-30 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0014_remove_estimated_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='User currently assigned to this quest', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quests', to=settings.AUTH_USER_MODEL),
        ),
    ]
