# Generated by Django 5.2.3 on 2025-06-30 06:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0015_quest_assigned_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['assigned_to', 'status'], name='quests_ques_assigne_557d69_idx'),
        ),
    ]
