# Generated by Django 5.2.3 on 2025-07-01 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0016_quest_quests_ques_assigne_557d69_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quest',
            name='max_participants',
        ),
    ]
