# Generated by Django 5.2.3 on 2025-07-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0017_remove_max_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='description',
            field=models.TextField(help_text='Maximum 2000 characters', max_length=2000),
        ),
    ]
