# Generated by Django 5.2.3 on 2025-07-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0018_add_description_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='questparticipant',
            name='application_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questparticipant',
            name='application_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questparticipant',
            name='application_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questparticipant',
            name='review_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='questparticipant',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
