# Generated by Django 5.2.3 on 2025-07-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0019_remove_unused_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questparticipant',
            name='application_date',
        ),
        migrations.RemoveField(
            model_name='questparticipant',
            name='application_id',
        ),
        migrations.RemoveField(
            model_name='questparticipant',
            name='application_message',
        ),
        migrations.RemoveField(
            model_name='questparticipant',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='questparticipant',
            name='reviewed_at',
        ),
    ]
