# Generated by Django 5.2.3 on 2025-07-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0022_add_quest_participations_related_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='difficulty',
            field=models.CharField(choices=[('initiate', 'Initiate'), ('adventurer', 'Adventurer'), ('champion', 'Champion'), ('mythic', 'Mythic')], default='initiate', max_length=10),
        ),
        migrations.AlterField(
            model_name='quest',
            name='xp_reward',
            field=models.PositiveIntegerField(choices=[(25, '25 XP (Initiate)'), (50, '50 XP (Adventurer)'), (100, '100 XP (Champion)'), (200, '200 XP (Mythic)')], default=25, help_text='XP points awarded upon completion'),
        ),
    ]
