# Generated by Django 5.2.3 on 2025-07-06 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0023_alter_quest_difficulty_alter_quest_xp_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='commission_fee',
            field=models.PositiveIntegerField(default=0, help_text='Commission fee taken by the system for this quest (auto-calculated, non-refundable)'),
        ),
    ]
