# Generated by Django 5.2.3 on 2025-07-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0024_quest_commission_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='If true, this quest is soft-deleted and hidden from normal queries.'),
        ),
    ]
