# Generated by Django 5.2.3 on 2025-07-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0026_questsubmissionfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questsubmissionfile',
            old_name='submission',
            new_name='quest_submission',
        ),
        migrations.AlterField(
            model_name='questsubmissionfile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
