# Generated by Django 5.2.3 on 2025-07-06 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0027_rename_submission_questsubmissionfile_quest_submission_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='QuestSubmissionFile',
        ),
    ]
