# Generated by Django 5.2.3 on 2025-07-06 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0029_add_description_link_to_questsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questsubmission',
            name='submission_text',
        ),
    ]
