# Generated by Django 5.2.3 on 2025-07-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0032_add_failed_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='status',
            field=models.CharField(choices=[('in-progress', 'In-Progress'), ('open', 'Open'), ('completed', 'Completed')], default='open', max_length=15),
        ),
    ]
