# Generated by Django 5.2.3 on 2025-07-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0033_remove_failed_quest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questsubmission',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('needs_revision', 'Needs Revision')], default='pending', max_length=15),
        ),
    ]
