# Generated by Django 5.2.3 on 2025-07-09 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0034_remove_superseded_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='category',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='quests.questcategory'),
        ),
    ]
