# Generated by Django 5.2.3 on 2025-07-04 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveField(
            model_name="message",
            name="sent_at",
        ),
    ]
