# Generated by Django 5.2.3 on 2025-07-07 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_messageattachment_messagereaction_userpresence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default='c6309d9b-8b20-4e1b-8b1f-91f3f27cbe5a', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation'),
            preserve_default=False,
        ),
    ]
