# Generated by Django 5.2.3 on 2025-07-09 17:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('quest_application', 'Quest Application'), ('quest_application_result', 'Quest Application Result'), ('kicked_from_quest', 'Kicked From Quest'), ('quest_disabled', 'Quest Disabled'), ('quest_deleted', 'Quest Deleted')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('quest_id', models.IntegerField(blank=True, null=True)),
                ('applicant', models.CharField(blank=True, max_length=255, null=True)),
                ('quest_title', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('result', models.CharField(blank=True, max_length=32, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
