# Generated by Django 5.2.3 on 2025-07-02 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('success', 'Success'), ('error', 'Error'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('hello, adventurer', 'Hello, Adventurer'), ('goodbye, adventurer', 'Goodbye, Adventurer'), ('permission denied', 'Permission Denied'), ('permission granted', 'Permission Granted'), ('email already in use', 'Email already in use'), ('quest updated successfully', 'Quest Updated Successfully'), ('you have been logged out', 'You have been logged out'), ('welcome to the peerquest tavern, your account has been created!', 'Welcome to the PeerQuest Tavern, Your Account has been Created!'), ('welcome back to the peerquest tavern', 'Welcome Back to the PeerQuest Tavern')], max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
