# Generated by Django 5.2.3 on 2025-07-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='application_id',
            field=models.IntegerField(blank=True, help_text='Related Application ID', null=True),
        ),
    ]
