# Generated by Django 5.2.3 on 2025-07-12 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_guild_id_notification_guild_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('quest_application', 'Quest Application'), ('quest_application_result', 'Quest Application Result'), ('kicked_from_quest', 'Kicked From Quest'), ('quest_disabled', 'Quest Disabled'), ('quest_deleted', 'Quest Deleted'), ('guild_event', 'Guild Notification'), ('guild_application_approved', 'Guild Application Approved'), ('guild_application_rejected', 'Guild Application Rejected'), ('guild_warned', 'Guild Warned'), ('guild_disabled', 'Guild Disabled'), ('guild_re_enabled', 'Guild Re-enabled'), ('warning_reset', 'Warning Reset')], max_length=32),
        ),
    ]
