# Generated by Django 5.2.3 on 2025-07-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='guild_id',
            field=models.CharField(blank=True, help_text='Related Guild ID', max_length=255, null=True),
        ),
    ]
